version: '3'
services:
  wp:
    build:
      context: .
    links:
      - mysql
    ports:
      - 8443:443
    volumes:
      - "./volume/app:/var/www/html/web/wp/wp-content"
      - "./volume/dump:/mnt/dump"
    environment:
      - SERVICE_PORT=8443
      - RDB_ENDPOINT=mysql:3306
      - RDB_USER=shifter
      - RDB_PASSWD=pass
      - SHIFTER_LOCAL=true
      - SERVICE_TYPE=generator # to simulate generator environment
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=shifter
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=wordpress
    # volumes:
    #   - "./volume/db:/var/lib/mysql"
